repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.3.3 # SEE: https://github.com/pre-commit/pre-commit/issues/3133

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args:
          [--line-length, "79"]

          #-   repo: https://github.com/igorshubovych/markdownlint-cli
          #    rev: v0.34.0
          #    hooks:
          #    -   id: markdownlint
  - repo: https://github.com/crate-ci/typos
    rev: v1.24.5
    hooks:
      - id: typos
