repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          [--line-length, "79"]

          #-   repo: https://github.com/igorshubovych/markdownlint-cli
          #    rev: v0.34.0
          #    hooks:
          #    -   id: markdownlint
  - repo: https://github.com/crate-ci/typos
    rev: v1.14.10
    hooks:
      - id: typos
